### ISSUE TITLE
Support for logical operator?

### ISSUE THREAD

**Issue by danielgindi** [aviaryan/BigEval.js#10]
How complicated would it be to add support for the logical OR and AND?
I basically want something like this: `X > 5 || (X < 2 && X > -3)`, to return `true` or `false`.

**Comment by aviaryan** [comment]
From README

> Factorial (!), Power (**), Modulo (%), And (&), Xor (^), Or (|) supported.

**Comment by aviaryan** [comment]
I don't think it would be difficult to add them. My last interaction with the codebase was quite some time ago so I can't be sure about this. I will try to implement it when I have free time. 
In the meanwhile, would you like to send a PR for this?
