### ISSUE TITLE
Add newer versions of Node to travis

### ISSUE THREAD

**Issue by aviaryan** [aviaryan/BigEval.js#15]
Also, we can remove non-major version like 4.1, 4.2 etc

**Comment by danielgindi** [comment]
Yes I think the minimum should be node 6

**Comment by aviaryan** [comment]
I am not sure about that. Any reason why you say so? @danielgindi

**Comment by danielgindi** [comment]
Because we 4 major versions later now, and in the node.js world - things move fast.
Look here: https://nodejs.org/en/ - 6.11 LTS recommended for most users
