### ISSUE TITLE
Expression instead of assignment in source

### ISSUE THREAD

**Issue by shuckster** [aviaryan/BigEval.js#16]
jslint threw up this issue on line 529 and 531:
https://github.com/aviaryan/BigEval.js/blob/master/BigEval.js#L529

	if (prevToken.value !== '+') {
		if (token.value === '-') {
			token.value === '+';
		} else {
			token.value === '-';
		}
	}

I'm guessing it should be:

	if (prevToken.value !== '+') {
		if (token.value === '-') {
			token.value = '+';
		} else {
			token.value = '-';
		}
	}

Thanks for the library. I'm about to try it out.

**Comment by shuckster** [comment]
You work quickly. :D

**Comment by aviaryan** [comment]
LOL. Had nothing else to do.
