### ISSUE TITLE
Security hole from window object

### ISSUE THREAD

**Issue by kpym** [aviaryan/BigEval.js#17]
We can read on the description page "... and in the end it looks into window's global namespace for the function". This looks dangerous, as can be dangerous to execute `eval` on untrusted string. Try for example to pass "alert(1)" to BigEval.

I think that by default access to global context should not be allowed for security reasons.

**Comment by aviaryan** [comment]
I think anyone can achieve similar results by going to any website, firing up Developer Tools and running JS in the console. How is this different?

**Comment by kpym** [comment]
If you parse your own strings there is no difference. But if you parse a string produced by somebody else in your browser or on your server (node.js) it is like letting somebody having access to your console or to your server.

**Comment by aviaryan** [comment]
I see. I didn't think about the server side issue. 

I think if we provide an option to disable `eval` and another option to disable `window` namespace functions, we can pretty much solve it.
