### ISSUE TITLE
How to load this library into browser page

### ISSUE THREAD

**Issue by JacobHornbeck** [aviaryan/BigEval.js#21]
I am trying to use this on a webpage that I am making, but I get an error when trying to load it. In the README it says to do
```javascript
<script src="BigEval.js"></script>
```
And obviously this won't work without it being installed, so I also did
```none
npm install bigeval
```
but it still doesn't work.

Is there a link to just link straight to the library code?

**Comment by aviaryan** [comment]
If you download [BigEval.js](https://github.com/aviaryan/BigEval.js/blob/master/BigEval.js) into the same directory as that HTML file, then the above `<script>` code should work.

`npm install bigeval` installs it into `node_modules` directory.

Yes, the file BigEval.js contains all the library code. https://github.com/aviaryan/BigEval.js/blob/master/BigEval.js
