### ISSUE TITLE
How to use this library in modern javascript frameworks like Nuxt3?

### ISSUE THREAD

**Issue by ParsaJR** [aviaryan/BigEval.js#32]
Hello. looks like this library can not be used in frameworks that following **ES Module**. because of this, **the 'require' keyword is not recognized for importing this library** ... you guys have any idea for workaround in this situation?

**Comment by aviaryan** [comment]
You can use the `import` keyword.

```js
import BigEval from "bigeval";

var Obj = new BigEval();
var result = Obj.exec("5! + 1e3 * (PI + E)");
console.log(result);
```

**Comment by ParsaJR** [comment]
Thank you !
