### ISSUE TITLE
Uninary operator working faulty

### ISSUE THREAD

**Issue by BhavyaGulati** [aviaryan/BigEval.js#9]
Hello

Please note that a!b is giving erroneous result as (a!)append(b)
eg: 3!6 is resulting in 66 
Furthermore a!(b) is performing addition as (a!)+(b)
eg: 4!3 is resulting in 27

Infact the proper outcome must be an Missing Operand error. Just found the bug, thought you must know.
Thank you.

**Comment by aviaryan** [comment]
Yes you are right. I am not handling many parsing errors now. Thanks for the input.

**Comment by BhavyaGulati** [comment]
I have made the necessary changes. Do let me know if you feel like integerating :D

**Comment by aviaryan** [comment]
> I have made the necessary changes. Do let me know if you feel like integerating :D

Send a PR and then we'll see. :smile:

**Comment by danielgindi** [comment]
This can now be closed :-)

**Comment by aviaryan** [comment]
Thanks @BhavyaGulati for reporting the issue.

**Comment by BhavyaGulati** [comment]
@danielgindi Thanks for the good work.
@aviaryan, your welcome :)

**Comment by BhavyaGulati** [comment]
Btw @aviaryan is there a way i can contact you or directly message you ?

**Comment by aviaryan** [comment]
@BhavyaGulati My [Twitter](https://twitter.com/aviaryan123) has open DM.
